baseURL = ""
languageCode = "en-us"
title = "Data and Lucas"
theme  = "luc-data-v1"
summaryLength = 40
# Main Menu
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-118288221-3"
enableRobotsTXT = "True"

[params]
    author = "Lucas "
    description = "Data Portfolio for Lucas Zapico"
    githubUsername = "LucasZapico"
    favicon = "img/favicon-32x32.ico"
    images = ["site-feature-image.jpg"]
    title = "Data.Lucas"


[taxonomies]
  tag = "tags"
  category = "categories"


[menu]

  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/#about"
    weight = 1

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Project"
    url = "/#project"
    weight = 1


  # [[menu.main]]
  #   name = "contact"
  #   url = "/contact/"
  #   weight = 1
